version: '3.8'

services:
 neo4j:
    hostname: neo4j
    image: neo4j:latest
    restart: always
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - .neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/password

 mongo:
    hostname: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .mongo_data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password